FROM ruby:2.2.0
RUN apt-get update && apt-get install -y \
	build-essential \
	libpq-dev

WORKDIR /usr/app
COPY Gemfile .
COPY Gemfile.lock . 
RUN bundle install
COPY webapp.rb .
COPY postgresdb.rb .
COPY webparamparser.rb .
CMD ["ruby", "webapp.rb"]
